# Generated by Django 5.0.7 on 2024-07-25 18:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakeUser',
            fields=[
                ('id', models.UUIDField(auto_created=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('job_title', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
